spring:
  datasource:
    url: jdbc:mysql://umcdb.cbc2u8q8u4en.ap-northeast-2.rds.amazonaws.com:3306/petwif
    username: root
    password: petwif0722
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update # update / create
        default_batch_fetch_size: 1000